#!/bin/bash
exec 2>&1
export PS4='${BASH_SOURCE}@${LINENO}(${FUNCNAME[0]}): '
set -x
export TMPDIR=$1
export ROLE=$2

# To force dpkg on Debian-based distros to play nice.
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C

read_attribute() {
    if [[ -f $TMPDIR/attrs/$1/attr ]]; then
        cat "$TMPDIR/attrs/$1/attr"
    else
        echo ""
    fi
}

write_attribute() {
    local loc="$TMPDIR/attrs/$1"
    mkdir -p "$loc"
    printf "%s" "$2" > "$loc/wall"
}

mkdir -p "$TMPDIR/attrs"
mkdir -p "$TMPDIR/logs"

for script in "$TMPDIR/$ROLE/"*.pp; do
    # error code of 2 means there were changes, which is normal - 1 or > 2 means errors
    /usr/local/bin/puppet apply --detailed-exitcodes "$script" --modulepath "$TMPDIR/modules" 2>&1 |tee  "$TMPDIR/logs/${script##*/}.log"
    ret=${PIPESTATUS[0]}
    ([[ $ret = 1 ]] || [[ $ret > 2 ]]) && exit 1
done
exit 0
