#!/bin/bash
SESSION="crowbar-docker"
NODE_DIR="$HOME/.cache/opencrowbar/tftpboot/nodes"

if [[ $0 = /* ]]; then
    tools="${0}"
elif [[ $0 = .*  || $0 = */* ]]; then
    tools="$(readlink -f "$PWD/$0")"
else
    echo "Cannot figure out where our tools are!"
    exit 1
fi
# This gets us to core
tools="${tools%/*}"

if ! which tmux &>/dev/null; then
    echo "Docker-slaves needs tmux installed!"
    exit 1
fi

if [[ ! $TMUX ]]; then
    tmux new-session -n control -s $SESSION "$0 $*"
    docker ps |grep '/crowbar-init' |awk '{print $1}' |xargs docker kill
    tmux kill-session -t $SESSION
    exit
fi
tmux set-option set-remain-on-exit on

on_admin() {
    ssh root@172.17.0.2 -- "$@"
}
crowbar() {
    on_admin /opt/opencrowbar/core/bin/crowbar "$@"
}

# Create our nodes.
echo "Creating docker nodes"
for ((n=1;n<=$1;n++)); do
    node="docker-$n.smoke.test"
    if [[ -x "$NODE_DIR/$node/crowbar-init" ]]; then
        echo "$node already created!"
        tmux new-window -d -n "$SESSION:$node" "$tools/docker-slave $node"
    else
        if crowbar nodes create "\"{\\\"name\\\": \\\"$node\\\"}\"" && \
            crowbar roles bind crowbar-docker-node to "$node" && \
            crowbar nodes commit "$node"; then
            echo "Created $node"
            tmux new-window -d -n "$SESSION:$node" "$tools/docker-slave $node"
        else
            break
        fi
    fi
done

echo "Leaving this session (with C-b d) will kill it and all the containers attached to it."
/bin/bash -i
